from .artifact_writer import (
    SYNTHESIS_ARTIFACTS,
    rebuild_synthesis_artifacts,
    render_argument_map_md,
    render_comparison_matrix_md,
    render_decision_memo_md,
    render_report_assembly_plan_md,
    render_uncertainty_boundaries_md,
)
from .comparison_matrix import infer_comparison_options, is_comparative_question
from .contracts import (
    ArgumentMap,
    ArgumentNode,
    ArgumentRelation,
    ComparisonCell,
    ComparisonDimension,
    ComparisonMatrix,
    DecisionMemo,
    FindingCluster,
    OpenQuestion,
    Recommendation,
    ReportAssemblyPlan,
    ResearchFinding,
    SynthesisInput,
    SynthesisOutput,
    UncertaintyBoundary,
)
from .outline_builder import cluster_findings, extract_findings

__all__ = [
    "SYNTHESIS_ARTIFACTS",
    "ArgumentMap",
    "ArgumentNode",
    "ArgumentRelation",
    "ComparisonCell",
    "ComparisonDimension",
    "ComparisonMatrix",
    "DecisionMemo",
    "FindingCluster",
    "OpenQuestion",
    "Recommendation",
    "ReportAssemblyPlan",
    "ResearchFinding",
    "SynthesisInput",
    "SynthesisOutput",
    "UncertaintyBoundary",
    "cluster_findings",
    "extract_findings",
    "infer_comparison_options",
    "is_comparative_question",
    "rebuild_synthesis_artifacts",
    "render_argument_map_md",
    "render_comparison_matrix_md",
    "render_decision_memo_md",
    "render_report_assembly_plan_md",
    "render_uncertainty_boundaries_md",
]
